#server port
server:
  port: 31100


#database connection
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/sreerastuDb
    username: postgres
    password: root
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

    hibernate:
      ddl-auto: update








#  format_sql: true
#
#
#    show-sql: true