#server port
server:
  port: 3100


#smtp configuration and database configuration
spring:
  mail:
    host: smtp.gmail.com
    port: 587
    protocol: smtp
    username: devisaikotari@gmail.com
    password: liqiodrybarvgjpx
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  datasource:
#    url: jdbc:postgresql://localhost:5432/sreerastuDb
    url: jdbc:postgresql://postgresdb.cu0ghcs3xhjo.us-east-1.rds.amazonaws.com:5432/sreerastuDb
    username: postgres
    password: Headway123
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

    hibernate:
      ddl-auto: update



#smpt configurations
#mail:
#  host: smtp.gmail.com
#  port: 587
#  protocol: smtp
#  username: devisaikotari@gmail.com
#  password: liqiodrybarvgjpx
#  properties:
#    mail:
#      smtp:
#        auth: true
#        starttls:
#          enable: true







#  format_sql: true
#
#
#    show-sql: true