#server port
server:
  port: 3100


#smtp configuration and database configuration
spring:
  main:
    allow-circular-references: true


  mail:
    host: smtp.gmail.com
    port: 587
    protocol: smtp
    username: devisaikotari@gmail.com
    password: toqqybbrwtpzfovq
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  datasource:
    url: jdbc:postgresql://localhost:5432/sreerastuDb
    #    url: jdbc:postgresql://postgresdb.cu0ghcs3xhjo.us-east-1.rds.amazonaws.com:5432/sreerastuDb

    username: postgres
    #    password: Headway123
    password: root
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

    hibernate:
      ddl-auto: update

#eureka configuration
eureka:
  instance:
    hostname: postgresdb.cu0ghcs3xhjo.us-east-1.rds.amazonaws.com
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://postgresdb.cu0ghcs3xhjo.us-east-1.rds.amazonaws.com:5432/eureka/



#Swagger
springdoc:
  swagger-ui:
    path: /swagger-ui.html





